graph 
    A["Tácticas de Disponibilidad"] --> B["Detectar Fallos"]

    
    B --> B1["Monitorear"]
    B --> B2["Ping/Echo"]
    B --> B3["Latido"]
    B --> B4["Marca de Tiempo"]
    B --> B5["Monitoreo de Condición"]
    B --> B6["Chequeo de Sanidad"]
    B --> B7["Votación"]
    B --> B8["Detección de Excepciones"]
    B --> B9["Auto-Prueba"]
    
    %% C --> E["Preparación y Reparación"]
    %% C --> F["Reintroducción"]
    
    %% E --> E1["Repuesto Redundante"]
    %% E --> E2["Reversión"]
    %% E --> E3["Manejo de Excepciones"]
    %% E --> E4["Actualización de Software"]
    %% E --> E5["Reintento"]
    %% E --> E6["Ignorar Comportamiento Defectuoso"]
    %% E --> E7["Degradación Gradual"]
    %% E --> E8["Reconfiguración"]
    
    %% F --> F1["Sombra"]
    %% F --> F2["Resincronización de Estado"]
    %% F --> F3["Reinicio Escalonado"]
    %% F --> F4["Reenvío Continuo"]
    
    %% D --> D1["Eliminación del Servicio"]
    %% D --> D2["Transacciones"]
    %% D --> D3["Modelo Predictivo"]


    %% D --> D4["Prevención de Excepciones"]
    %% D --> D5["Aumento del Conjunto de Competencias"]

    style A fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B1 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B2 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B3 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B4 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B5 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B6 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B7 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B8 fill:#FFEB3B,stroke:#000,stroke-width:1px
    style B9 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E fill:#FFEB3B,stroke:#000,stroke-width:1px

    %% style F fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E1 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E2 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E3 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E4 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E5 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E6 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E7 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style E8 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style F1 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style F2 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style F3 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style F4 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style D1 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style D2 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style D3 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style D4 fill:#FFEB3B,stroke:#000,stroke-width:1px
    %% style D5 fill:#FFEB3B,stroke:#000,stroke-width:1px

