---
title: Ciclo de resolución de problemas de Polya
---

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': 'yellow',
      'primaryTextColor': 'green',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F8B229',
      'secondaryColor': '#006100',
      'tertiaryColor': '#fff'
    }
  }
}%%


flowchart TD;
    1[Entender el problema];
    2[Encontrar o diseñar un plan];
    3[Ejecutar el plan];
    4[Revisar el resultado y ver que aprendimos];
    1-->2-->3-->4-->1;
